# Generated by Django 5.2.7 on 2025-10-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('text_file', models.FileField(blank=True, null=True, upload_to='extracted_texts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('text_content', models.TextField(blank=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='extracted_texts/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('language', models.CharField(default='uk', max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OCR Document',
                'verbose_name_plural': 'OCR Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('language', models.CharField(default='uk', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='ocr_tts.extractedtext')),
            ],
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='image_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='ocr_tts.imagedocument'),
        ),
    ]
