# Generated by Django 5.2.7 on 2025-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='tts_provider',
            field=models.CharField(choices=[('gtts', 'Google TTS (gTTS)'), ('gemini', 'Google Gemini TTS')], default='gtts', max_length=10),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='tts_voice',
            field=models.CharField(blank=True, default='Zephyr', max_length=50),
        ),
    ]
