# Generated by Django 5.2.7 on 2025-10-15 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0002_ocrdocument_tts_provider_ocrdocument_tts_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='uk', max_length=10)),
                ('tts_provider', models.CharField(choices=[('gtts', 'Google TTS (gTTS)'), ('gemini', 'Google Gemini TTS')], default='gtts', max_length=10)),
                ('tts_voice', models.CharField(blank=True, default='Zephyr', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('text_content', models.TextField(blank=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='extracted_texts/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr_tts.document')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
