# Generated by Django 5.2.7 on 2025-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0003_document_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='document',
            name='audio_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='audio_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='combined_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/audio/'),
        ),
        migrations.AddField(
            model_name='document',
            name='combined_text_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/texts/'),
        ),
    ]
