# Generated by Django 5.2.7 on 2025-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0004_remove_page_audio_file_document_audio_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_languages',
            field=models.CharField(default='uk', help_text='Comma-separated OCR language codes (e.g., uk,en)', max_length=100),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='ocr_languages',
            field=models.CharField(default='uk', help_text='Comma-separated OCR language codes', max_length=100),
        ),
    ]
