# Generated by Django 5.2.7 on 2025-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0005_document_ocr_languages_ocrdocument_ocr_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='final_text',
            field=models.TextField(blank=True, help_text='Combined text with smart sentence merging and page dividers'),
        ),
    ]
