# Generated by Django 5.2.7 on 2025-10-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_tts', '0006_document_final_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField()),
                ('text_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='ocr_tts.document')),
            ],
            options={
                'verbose_name': 'Text Block',
                'verbose_name_plural': 'Text Blocks',
                'ordering': ['document', 'block_number'],
                'unique_together': {('document', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='BlockAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='block_audio/')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Audio duration in milliseconds', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, help_text='Last regeneration timestamp', null=True)),
                ('text_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='ocr_tts.textblock')),
            ],
            options={
                'verbose_name': 'Block Audio',
                'verbose_name_plural': 'Block Audios',
            },
        ),
    ]
